#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Lesson")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void UpdateJB_khxx(JB_khxx instance);
  partial void DeleteJB_khxx(JB_khxx instance);
  partial void InsertJB_gysxx(JB_gysxx instance);
  partial void UpdateJB_gysxx(JB_gysxx instance);
  partial void DeleteJB_gysxx(JB_gysxx instance);
  partial void InsertJB_SF(JB_SF instance);
  partial void UpdateJB_SF(JB_SF instance);
  partial void DeleteJB_SF(JB_SF instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LessonConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<JB_khxx> JB_khxx
	{
		get
		{
			return this.GetTable<JB_khxx>();
		}
	}
	
	public System.Data.Linq.Table<JB_gysxx> JB_gysxx
	{
		get
		{
			return this.GetTable<JB_gysxx>();
		}
	}
	
	public System.Data.Linq.Table<JB_SF> JB_SF
	{
		get
		{
			return this.GetTable<JB_SF>();
		}
	}
	
	private void InsertJB_khxx(JB_khxx obj)
	{
		this.UP_JB_khxx_ADD(obj.id, obj.mingcheng, obj.dianhua, obj.chuanzhen, obj.dizhi);
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllData")]
	public ISingleResult<GetAllDataResult> GetAllData()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetAllDataResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_JB_khxx1_GetList")]
	public ISingleResult<sp_JB_khxx1_GetListResult> sp_JB_khxx1_GetList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name);
		return ((ISingleResult<sp_JB_khxx1_GetListResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MultiResultSet")]
	public ISingleResult<sp_MultiResultSetResult> sp_MultiResultSet()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_MultiResultSetResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UP_JB_khxx_ADD")]
	public int UP_JB_khxx_ADD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string mingcheng, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string dianhua, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string chuanzhen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dizhi)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, mingcheng, dianhua, chuanzhen, dizhi);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UP_JB_khxx_Delete")]
	public int UP_JB_khxx_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UP_JB_khxx_GetList")]
	public ISingleResult<UP_JB_khxx_GetListResult> UP_JB_khxx_GetList()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<UP_JB_khxx_GetListResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JB_khxx")]
[Serializable()]
public partial class JB_khxx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _id;
	
	private string _mingcheng;
	
	private string _dianhua;
	
	private string _chuanzhen;
	
	private string _dizhi;
	
	private System.Nullable<int> _sfid;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnmingchengChanging(string value);
    partial void OnmingchengChanged();
    partial void OndianhuaChanging(string value);
    partial void OndianhuaChanged();
    partial void OnchuanzhenChanging(string value);
    partial void OnchuanzhenChanged();
    partial void OndizhiChanging(string value);
    partial void OndizhiChanged();
    partial void OnsfidChanging(System.Nullable<int> value);
    partial void OnsfidChanged();
    #endregion
	
	public JB_khxx()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mingcheng", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string mingcheng
	{
		get
		{
			return this._mingcheng;
		}
		set
		{
			if ((this._mingcheng != value))
			{
				this.OnmingchengChanging(value);
				this.SendPropertyChanging();
				this._mingcheng = value;
				this.SendPropertyChanged("mingcheng");
				this.OnmingchengChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianhua", DbType="VarChar(15)")]
	public string dianhua
	{
		get
		{
			return this._dianhua;
		}
		set
		{
			if ((this._dianhua != value))
			{
				this.OndianhuaChanging(value);
				this.SendPropertyChanging();
				this._dianhua = value;
				this.SendPropertyChanged("dianhua");
				this.OndianhuaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuanzhen", DbType="VarChar(15)")]
	public string chuanzhen
	{
		get
		{
			return this._chuanzhen;
		}
		set
		{
			if ((this._chuanzhen != value))
			{
				this.OnchuanzhenChanging(value);
				this.SendPropertyChanging();
				this._chuanzhen = value;
				this.SendPropertyChanged("chuanzhen");
				this.OnchuanzhenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dizhi", DbType="VarChar(50)")]
	public string dizhi
	{
		get
		{
			return this._dizhi;
		}
		set
		{
			if ((this._dizhi != value))
			{
				this.OndizhiChanging(value);
				this.SendPropertyChanging();
				this._dizhi = value;
				this.SendPropertyChanged("dizhi");
				this.OndizhiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sfid", DbType="Int")]
	public System.Nullable<int> sfid
	{
		get
		{
			return this._sfid;
		}
		set
		{
			if ((this._sfid != value))
			{
				this.OnsfidChanging(value);
				this.SendPropertyChanging();
				this._sfid = value;
				this.SendPropertyChanged("sfid");
				this.OnsfidChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JB_gysxx")]
public partial class JB_gysxx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _id;
	
	private string _danwei;
	
	private string _lianxiren;
	
	private string _lianxidianhua;
	
	private string _chuanzhen;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OndanweiChanging(string value);
    partial void OndanweiChanged();
    partial void OnlianxirenChanging(string value);
    partial void OnlianxirenChanged();
    partial void OnlianxidianhuaChanging(string value);
    partial void OnlianxidianhuaChanged();
    partial void OnchuanzhenChanging(string value);
    partial void OnchuanzhenChanged();
    #endregion
	
	public JB_gysxx()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danwei", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string danwei
	{
		get
		{
			return this._danwei;
		}
		set
		{
			if ((this._danwei != value))
			{
				this.OndanweiChanging(value);
				this.SendPropertyChanging();
				this._danwei = value;
				this.SendPropertyChanged("danwei");
				this.OndanweiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lianxiren", DbType="VarChar(16)")]
	public string lianxiren
	{
		get
		{
			return this._lianxiren;
		}
		set
		{
			if ((this._lianxiren != value))
			{
				this.OnlianxirenChanging(value);
				this.SendPropertyChanging();
				this._lianxiren = value;
				this.SendPropertyChanged("lianxiren");
				this.OnlianxirenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lianxidianhua", DbType="VarChar(15)")]
	public string lianxidianhua
	{
		get
		{
			return this._lianxidianhua;
		}
		set
		{
			if ((this._lianxidianhua != value))
			{
				this.OnlianxidianhuaChanging(value);
				this.SendPropertyChanging();
				this._lianxidianhua = value;
				this.SendPropertyChanged("lianxidianhua");
				this.OnlianxidianhuaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuanzhen", DbType="VarChar(15)")]
	public string chuanzhen
	{
		get
		{
			return this._chuanzhen;
		}
		set
		{
			if ((this._chuanzhen != value))
			{
				this.OnchuanzhenChanging(value);
				this.SendPropertyChanging();
				this._chuanzhen = value;
				this.SendPropertyChanged("chuanzhen");
				this.OnchuanzhenChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JB_SF")]
public partial class JB_SF : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _mingcheng;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmingchengChanging(string value);
    partial void OnmingchengChanged();
    #endregion
	
	public JB_SF()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mingcheng", DbType="VarChar(20)")]
	public string mingcheng
	{
		get
		{
			return this._mingcheng;
		}
		set
		{
			if ((this._mingcheng != value))
			{
				this.OnmingchengChanging(value);
				this.SendPropertyChanging();
				this._mingcheng = value;
				this.SendPropertyChanged("mingcheng");
				this.OnmingchengChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class GetAllDataResult
{
	
	private string _id;
	
	private string _name;
	
	private string _dianhua;
	
	private string _chuanzhen;
	
	private string _address;
	
	public GetAllDataResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianhua", DbType="VarChar(50)")]
	public string dianhua
	{
		get
		{
			return this._dianhua;
		}
		set
		{
			if ((this._dianhua != value))
			{
				this._dianhua = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuanzhen", DbType="VarChar(50)")]
	public string chuanzhen
	{
		get
		{
			return this._chuanzhen;
		}
		set
		{
			if ((this._chuanzhen != value))
			{
				this._chuanzhen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this._address = value;
			}
		}
	}
}

public partial class sp_JB_khxx1_GetListResult
{
	
	private string _id;
	
	private string _name;
	
	private string _dianhua;
	
	private string _chuanzhen;
	
	private string _address;
	
	public sp_JB_khxx1_GetListResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianhua", DbType="VarChar(50)")]
	public string dianhua
	{
		get
		{
			return this._dianhua;
		}
		set
		{
			if ((this._dianhua != value))
			{
				this._dianhua = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuanzhen", DbType="VarChar(50)")]
	public string chuanzhen
	{
		get
		{
			return this._chuanzhen;
		}
		set
		{
			if ((this._chuanzhen != value))
			{
				this._chuanzhen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this._address = value;
			}
		}
	}
}

public partial class sp_MultiResultSetResult
{
	
	private string _id;
	
	private string _name;
	
	private string _dianhua;
	
	private string _chuanzhen;
	
	private string _address;
	
	public sp_MultiResultSetResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianhua", DbType="VarChar(50)")]
	public string dianhua
	{
		get
		{
			return this._dianhua;
		}
		set
		{
			if ((this._dianhua != value))
			{
				this._dianhua = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuanzhen", DbType="VarChar(50)")]
	public string chuanzhen
	{
		get
		{
			return this._chuanzhen;
		}
		set
		{
			if ((this._chuanzhen != value))
			{
				this._chuanzhen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this._address = value;
			}
		}
	}
}

public partial class UP_JB_khxx_GetListResult
{
	
	private string _id;
	
	private string _mingcheng;
	
	private string _dianhua;
	
	private string _chuanzhen;
	
	private string _dizhi;
	
	private System.Nullable<int> _sfid;
	
	public UP_JB_khxx_GetListResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mingcheng", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string mingcheng
	{
		get
		{
			return this._mingcheng;
		}
		set
		{
			if ((this._mingcheng != value))
			{
				this._mingcheng = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianhua", DbType="VarChar(15)")]
	public string dianhua
	{
		get
		{
			return this._dianhua;
		}
		set
		{
			if ((this._dianhua != value))
			{
				this._dianhua = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuanzhen", DbType="VarChar(15)")]
	public string chuanzhen
	{
		get
		{
			return this._chuanzhen;
		}
		set
		{
			if ((this._chuanzhen != value))
			{
				this._chuanzhen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dizhi", DbType="VarChar(50)")]
	public string dizhi
	{
		get
		{
			return this._dizhi;
		}
		set
		{
			if ((this._dizhi != value))
			{
				this._dizhi = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sfid", DbType="Int")]
	public System.Nullable<int> sfid
	{
		get
		{
			return this._sfid;
		}
		set
		{
			if ((this._sfid != value))
			{
				this._sfid = value;
			}
		}
	}
}
#pragma warning restore 1591
