// <auto-generated />
using _03LinqToSQL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace _03LinqToSQL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20180625074505_addtablse")]
    partial class addtablse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_03LinqToSQL.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("_03LinqToSQL.Model.CustomerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("Cid");

                    b.Property<int?>("CustomerId");

                    b.Property<string>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerInfos");
                });

            modelBuilder.Entity("_03LinqToSQL.Model.CustomerMore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CIid");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CustomerMores");
                });

            modelBuilder.Entity("_03LinqToSQL.Model.CustomerInfo", b =>
                {
                    b.HasOne("_03LinqToSQL.Model.Customer", "Customer")
                        .WithMany("CustomerInfos")
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
